iohttp.server:Error handling request from 10.101.36.249
Traceback (most recent call last):
  File "/home/block_bi/miniconda3/envs/nerfstream/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
  File "/home/block_bi/miniconda3/envs/nerfstream/lib/python3.10/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
  File "/home/block_bi/avatar/LiveTalking/app.py", line 90, in offer
    params = await request.json()
  File "/home/block_bi/miniconda3/envs/nerfstream/lib/python3.10/site-packages/aiohttp/web_request.py", line 695, in json
    return loads(body)
  File "/home/block_bi/miniconda3/envs/nerfstream/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/block_bi/miniconda3/envs/nerfstream/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/block_bi/miniconda3/envs/nerfstream/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

